apiVersion: eks.aws.upbound.io/v1beta1
kind: ClusterAuth
metadata:
  name: workload-cluster
spec:
  forProvider:
    clusterName: murph-workload
    region: eu-west-1
  writeConnectionSecretToRef:
    name: murph-workload-kubeconfig
    namespace: crossplane-system
