apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      key: kubeconfig
      name: murph-workload-kubeconfig
      namespace: crossplane-system
    