apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.platform.upbound.io
spec:
  claimNames:
    kind: Database
    plural: databases
  group: platform.upbound.io
  names:
    categories:
    - crossplane
    kind: XDatabase
    plural: xdatabases
  versions:
  - name: v1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Database is the Schema for the Database API.
        properties:
          spec:
            description: DatabaseSpec defines the desired state of Database.
            properties:
              paramters:
                properties:
                  engine:
                    type: string
                type: object
            type: object
          status:
            description: DatabaseStatus defines the observed state of Database.
            type: object
        required:
        - spec
        type: object
    served: true
