apiVersion: platform.upbound.io/v1
kind: XAppDeployment
metadata:
  name: example
spec: 
  application:
    name: guestbook-ui
    image: gcr.io/heptio-images/ks-guestbook-demo:0.2
  resources:
  - name: images
    type: s3
    s3:
      bucketName: murph-images-bucket
  - name: database
    type: postgres
    postgres: {}

